# -*- coding: utf-8 -*-
"""Pytorch_Lightning_Loading

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13McKlllSekctVvdWnALD-fcNh3jel_8L
"""

import os, sys
from google.colab import drive
drive.mount('/content/drive')
nb_path = '/content/notebooks'
os.symlink('/content/drive/My Drive/Colab Notebooks', nb_path)
sys.path.insert(5, nb_path)

import pytorch_lightning